### ISSUE TITLE
1. 동일한 팀 여러 개 생김 (이유 불명, 팀 만드는 중에 생긴 건 아니었음 갑자기 생김)

### ISSUE THREAD

**Issue by GwonPyo** [klab-mtot/mtot-backend#29]
![image](https://github.com/klab-mtot/mtot-backend/assets/85156021/1a9b6454-9658-439b-a610-aaf7d8133479)

**Comment by donghoony** [comment]
#30 이랑 같은 문제, #33 으로 해결
