### ISSUE TITLE
2. team에 다른 멤버 추가 시 동일 팀 여러 개 생성 + 해당 멤버한테는 그룹 안보임

### ISSUE THREAD

**Issue by GwonPyo** [klab-mtot/mtot-backend#30]
1. 여러 개 생성
![image](https://github.com/klab-mtot/mtot-backend/assets/85156021/3bf6ced4-4f3f-453f-8b22-3be158edb27b)

---
2. 해당 멤버한테는 그룹 안 생김(2는 본인이 만들었던거, 1은 생겨야 하는거. 근데 1이 안 생김.)
![image](https://github.com/klab-mtot/mtot-backend/assets/85156021/52c2784c-2b31-4d04-afcf-68b74d447e42)

**Comment by donghoony** [comment]
수정했음
