### ISSUE TITLE
3. post 추가 시 무한 루프? 인지 모르겠지만 문제 발생

### ISSUE THREAD

**Issue by GwonPyo** [klab-mtot/mtot-backend#31]
post 추가 후 /journey/{journeyId}로 정보 가져옴. 아래와 같이 post가 이상하게 만들어짐.
![image](https://github.com/klab-mtot/mtot-backend/assets/85156021/5dcf1d32-3838-40d5-8eb3-ef342acd8958)

**Comment by donghoony** [comment]
journeyservice에서 getJourneyList의 문제 -> getPost수정해야함

**Comment by GwonPyo** [comment]
![image](https://github.com/klab-mtot/mtot-backend/assets/85156021/13af80d4-d64e-4c00-82a6-d2f770d23e57)

어노테이션으로 해결하긴 했어용

**Comment by GwonPyo** [comment]
pr 보내겠습다!

**Comment by donghoony** [comment]
#36
