### ISSUE TITLE
4. 동일 핀 추가 됨

### ISSUE THREAD

**Issue by GwonPyo** [klab-mtot/mtot-backend#35]
지금 post 수정 코드가 서버엔 있어서 일단 로컬로 돌렸습니다.
pin은 develop 코드와 동일한데 아래와 같이 1번과 4번 pin이 동일하게 들어갑니다 

![image](https://github.com/klab-mtot/mtot-backend/assets/85156021/9ea04f74-1bf4-487a-ba40-bd3b84729675)

---

서버에서도 동일한 에러

![image](https://github.com/klab-mtot/mtot-backend/assets/85156021/ed0f8f51-c170-4355-8195-48b9ce1b4efe)

**Comment by GwonPyo** [comment]
연속해서 같은 위치를 입력하면 추가되지 않지만 다른 핀 추가 후 돌아오면 동일 핀이 찍힙니다

**Comment by donghoony** [comment]
다른 핀 추가 후 돌아오면 동일 핀이 찍히는 건 의도된 사항입니다.
앱 쪽에서  4-5분마다 리퀘스트를 찍을텐데, 멀리 갔다가 다시 돌아오면 핀이 새로 생기는 게 맞음
최근 핀으로부터 100m 이상 떨어지면 핀이 찍힘
